# Generated by Django 2.0.7 on 2019-06-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Price of product in cents'),
            preserve_default=False,
        ),
    ]
