# Generated by Django 2.0.7 on 2019-06-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productprice_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='name',
            field=models.CharField(default='', help_text='Name of price change', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(help_text='Default price of product in cents'),
        ),
    ]
